version: "3.4"

services:
  identity:
    image: ${DOCKER_REGISTRY-}identity
    build:
      context: src
      dockerfile: SaM.AnyDeals.IdentityServer/Dockerfile
  backend:
    image: ${DOCKER_REGISTRY-}backend
    build:
      context: src
      dockerfile: SaM.AnyDeals.API/Dockerfile
  client:
    image: ${DOCKER_REGISTRY-}client
    build:
      context: src
      dockerfile: SaM.AnyDeals.Web/Dockerfile
  proxy:
    image: nginx:latest
