version: '3.4'

services:
  database:
    ports:
      - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql/data
  backend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - UseDockerDB=true
      - JWTSecurityKey=!123__MyJWTSecretKey__123!
      - BONSAI_URL=https:\\o0hr0acl24:hp1tmflug4@pine-530439672.eu-west-1.bonsaisearch.net:443
    ports:
      - "5000:80"
  client:
    ports:
      - "5001:3000"
    volumes:
      - ./src/SaM.AnyDeals.Web/:/app:delegated
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - WDS_SOCKET_HOST=0.0.0.0
      - WDS_SOCKET_PORT=0
  proxy:
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf 
    ports:
      - "8080:80" 