version: '3.4'

services:
  database:
    ports:
      - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql/data
  backend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - JWTSecurityKey=!123__MyJWTSecretKey__123!
    ports:
      - "5000:80"
  client:
    ports:
      - "5001:3000"
  proxy:
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf 
    ports:
      - "8080:80" 