version: '3.4'

services:
  database:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=ChangeMe123!
  backend:
    image: ${DOCKER_REGISTRY-}backend
    build:
      context: src/SaM.AnyDeals.API
      dockerfile: Dockerfile
    depends_on:
      - database
  client:
    image: ${DOCKER_REGISTRY-}client
    build:
      context: src/SaM.AnyDeals.Web
      dockerfile: Dockerfile
  proxy:
    image: nginx:latest