version: "3.4"

services:
  database:
    ports:
      - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql/data
  identity:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - UseDockerDB=true
      - UseProxy=true
      - BONSAI_URL=https:\\o0hr0acl24:hp1tmflug4@pine-530439672.eu-west-1.bonsaisearch.net:443
      - ConnectionString=Server=database;Database=SaMAnyDeals;User=SA;Password=ChangeMe123!;Encrypt=false
    ports:
      - "5003:80"
  backend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - UseDockerDB=true
      - UseProxy=true
      - JWTSecurityKey=!123__MyJWTSecretKey__123!
      - BONSAI_URL=https:\\o0hr0acl24:hp1tmflug4@pine-530439672.eu-west-1.bonsaisearch.net:443
      - MIGRATION_DATA_FOLDER=/app/Migrations/Data/
      - ConnectionString=Server=database;Database=SaMAnyDeals;User=SA;Password=ChangeMe123!;Encrypt=false
    ports:
      - "5000:80"
    volumes:
      - ./data:/app/Migrations/Data:delegated
  client:
    ports:
      - "5001:3000"
    volumes:
      - ./src/SaM.AnyDeals.Web/:/app:delegated
      - /app/node_modules
  proxy:
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
